- README.md
Olá,
Recentemente eu havia aberto um PR que foi recusado. Essa é a minha segunda tentativa de incorporação. 
Por favor me avise se algo ainda estiver errado.
Tenho total interesse em divulgar o projeto neste repositório.
> add english talking api

- README.md
adiciona pacote go para gerar link de pagamento e qrcode pix estático
> adiciona pacote golang pix

- README.md
Gostaria de adicionar meu projeto pipconf à lista de projetos brasileiros 😁
> Pipconf - gerenciador de configurações para o pip

- README.md
Adicionando os projetos C#:
- [BancosBrasileiros](https://github.com/GuiBranco/BancosBrasileiros): Lista de bancos brasileiros atualizadas diariamente
- [CrispyWaffle](https://github.com/GuiBranco/CrispyWaffle): Toolkit / mini-framework para C#
> Add BancosBrasileiros (C#) and CrispyWaffle (C#)

- README.md
AtomicReact is a framework to build Web Apps with atomicity concept
> Add AtomicReact project

- README.md
- Adicionando projeto open source LattesIdentifier service;
- Se trata de uma API RESTful em Python para validação do número identificador Lattes utilizando Flask e MySQL/CSV para fins de consulta. Documentação em Flasgger.
- https://github.com/gogoncalves/lattes-identifier-service
> Add LattesIdentifier Service

- README.md
PythonREST is the next level REST API Generator for Python projects! With it, you can create a full application with a single CLI command and experience months of project development in a few seconds.
> Adding PythonREST project

- README.md
🐷 [**Poku**](https://github.com/wellwelwel/poku) é um projeto focado em execução e criação de testes automatizados para **Node.js**, **TypeScript**, **Bun** e **Deno**, abstraindo as complexidades para si e tornando algo que hoje pode ser muitas vezes complexo e até difícil, em um aprendizado leve, simples e até amigável para todos os desenvolvedores.
No _GIF_ abaixo estão dois exemplos reais, o primeiro usando o _tester_ mais popular atualmente para **Node.js** e em seguida, o [**Poku**](https://github.com/wellwelwel/poku), ambos chegando no mesmo resultado em um simples teste de `"1 é igual a 1"` com **ESM** (`mjs`) puro:
---
- Atualmente, o [**Poku**](https://github.com/wellwelwel/poku) é o _tester_ usado no [**MySQL2**](https://github.com/sidorares/node-mysql2/pull/2472) 🎉
- Também …
> add poku to list

- README.md
Oi pessoal!
- O meu fork é esse: https://github.com/lucasnuic/opensource-br  
- Veja a issue aqui: https://github.com/backend-br/opensource-br/issues/63  
- eu falei com o @vgeruso e que parece que não existe problema em adicionar, e ficaria feliz com uma iniciativa aberta.
> add board in repo

- README.md
Mais uma colaboração aqui para a comunidade backend-br no projeto opensource-br. adicionei o link de referência ao openboleto-br que é um projeto de biblioteca que gera boleto e é feita por devs do brasil.
Espero que gostem e curtem. vale bastante apena, e espero ajudar essa comunidade maravilhosa.
> add "openboleto" in readme

- README.md
Adicionando sistema operacional br chamado biglinux no projeto opensource-br. Esse é um projeto tão importante quanto o duzerulinux. O BigLinux teve até participação acho que no evento da campus party. É um projeto bem legal, é parecido com a ideia do windows-like, a experiência de instalar e remover programas é bem facilitada. Acho que faz sentido mostrar que existem ótimos desenvolvedores brasileiros que ajudam no desenvolvimento de distros linux.
> add biglinux in opensource-br

- README.md
Pessoal, voltei. E ainda mais motivado. Vamos unir forças para o open source br. A breve história do visual g: - *"Observando a dificuldade dos estudantes de Computação em entender programação, o ex-aluno do Câmpus Gaspar e professor universitário, Antônio Carlos Nicolodi, criou o Visualg 3.0, um software, gratuito, que permite ao usuário acompanhar, passo a passo, o processo de criação de aplicativos para computadores e outros dispositivos eletrônicos, como celulares ou tablets."* Entender visual g, pode levar a conhecer várias linguagens de programação, e não somente uma. Existem implementações do visual g, por isso deixei a implementação oficial que está no sourceforge. 
Com o apoio e o consenso da comunidade, posso adicionar esses projetos …
> add visualg

- README.md
"[Dev-ES/awesome-finance](https://github.com/Dev-ES/awesome-finance)" a ideia é reunir links sobre canais de finanças, contabilidade, economia para que todos tenham acesso a informação geral, sem que para isso pague fortunas para cursos de educação financeira. inclusive, estou ajudando. ainda não enviei o pull-request, mas irei fazê-lo em breve, depois que adicionarem o visualg. Aqui eu vou postar caso essa outra comunidade me aprove sobre código aberto x software fechado na gestão financeira.
> add awesome-finance

- README.md
🇧🇷 Uma coleção de projetos open source incríveis construídos por desenvolvedores brasileiros. É bem parecido com o opensource-br, só que pelo histórico de commits parece um projeto recente. Adicionei para melhorar o SEO deste repositório e do outro já que ambos falam a mesma coisa, embora esse seja mais focado no backend, e o outro tanto frontend quanto backend.
edit: o estagiário esqueceu de fazer backup e apagou com del a tabela :(
> awesome-made-by-brazilians

- README.md
Esse repo reune informações como gerenciar código fonte, as técnicas como model-view-controller, clean-code e muitas outros. É antigo, mas valioso. Se aceitarem o pull-request, vou achar que posso continuar enviando contribuições aqui. do contrário, vou me desligar do projeto. por achar que fui inconveniente ou que não ajudei em nada.
> add design-patterns-for-humans-brazilian-portuguese

- README.md
📚 Central de conhecimentos sobre a linguagem de programação Go
> aprenda-go

- README.md
"Uma escola aberta, da comunidade, para a comunidade!" É um projeto para ensinar programação: frontend e  backend de forma gratuita.
> add openschoolbr

- README.md
adicionando um portal de tecnologia aberta
> buteco-tech

- README.md
Esse é o espaço para divulgação de projetos open-source brasileiros. Aqui está uma biblioteca que uso muito chamada pypicpay.
> add pypicpay

- README.md
O KiddieOS é um sistema open-source e livre pra distribuir e modificar, sem fins lucrativos, similar ao Linux. É um sistema didático mais focado no público estudante, em especial dos que estudam sistemas operacionais, Assembly e C. Atualmente ele ainda não tem a linguagem C como desenvolvimento, mas terá no âmbito de aplicações e outros tipos de drivers alternativos no formato ELF que os programadores/colaboradores venha a criar, após eu dar o suporte ao formato ELF.
obs: Houve vários sistemas operacionais desenvolvidos no Brasil. Aqui adiciono um sistema operacional brasileiro que é uma alternativa ao free-dos, dos, ms-dos e afins. Quem desenvolve sistema operacional, sabe muito de backend e sabe o quão é trabalhoso é gerencia-lo. Se gostarem posso adicionar mais coisas relacionadas …
> add KiddieOS

- README.md
Esse é o espaço para divulgação de projetos open-source brasileiros. Aqui divulgo a biblioteca js para máscara de valores financeiros. o que faço no backend precisa disso, e é mantida por um desenvolvedor brasileiro que é engenheiro de software.
> simple mask money

- README.md
Adicionando a comunidade e o repositório da perifacode.
> perifacode

- README.md
Grupo informal que reúne pessoas que defendem direitos civis e sociais através da criptografia ou tecnologia. Na verdade, é uma vertente da cultura hacker mais afeita a ação política individual para o coletivo ou do coletivo ao individual. Surgem nos anos 1990 dizendo que a única maneira de manter a privacidade na era da informação é com uma criptografia forte. Uma das tecnologias que surge nesse sentido é a ideia das criptomoedas, comunicação p2p e outros. Boa parte da internet hoje nasceu nos anos 90.
> cypherpunks

- README.md
Semelhante ao opensource-br, mas com devs que utiliza projetos br em todo mundo. Ou projetos que boa partes das pessoas utiliza no brasil e no mundo.
> add listamaravilhosaopensource

- README.md
Tudo segue conforme proposto agora. criei um arquivo de contribuição falando como ajudar o repo.
> jornada-engenheiro-de-software
